// Generated by track editor Unity project
const vec3 Xc0 = vec3(-8.66,0.13,46.95),Xc1 = vec3(14.46,8.03,156.05),Xc2 = vec3(56.37,7.93,159.73),Xc3 = vec3(113.46,9.77,200.96);
const vec4 Xf0 = vec4(0,0,0,1),Xf1 = vec4(0.12,-0.468,0.199,0.853),Xf2 = vec4(0.07,-0.704,0.07,0.704),Xf3 = vec4(0,-0.277,0,0.961),Xp0 = vec4(106.3,9.6,192.35,22.3);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.x / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.119,0.,0.,0.993,-8.6,-2.19,-46.66 ,3.549,0.5,5.093 ) );
if( mod( g_traceBits.x / i_BIT7, 2. ) >= 1. )
d = min2( d, sdObj0( p, -0.25,-0.551,-0.688,0.401,-80.1,-15.9,120.65 ,18.917,18.917,18.917 ) );
if( mod( g_traceBits.x / i_BIT8, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,-8.6,8.2,79.6 ,4.,20.,80.,2.,0. ) );
if( mod( g_traceBits.x / i_BIT9, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.109,-0.195,-0.44,0.87,10.53,-2.73,87.08 ,5.,5.,5. ) );
if( mod( g_traceBits.y / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.,0.,0.,1.,106.,-9.6,172.85 ,20.,20.,20. ) );
if( mod( g_traceBits.y / i_BIT1, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.,1.,-8.6,8.2,119.57 ,4.,-40.,-0.5,0.,2. ) );
if( mod( g_traceBits.y / i_BIT2, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.707,0.,0.707,71.4,8.2,159.56 ,4.,20.,-80.,2.,0. ) );
if( mod( g_traceBits.y / i_BIT3, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj1( p, 0.,0.,0.,1.,-8.6,0.21,-36.87 ,4.,50.,0.,2.,0. ),sdObj0( p, 0.313,0.,0.,0.95,-8.6,-2.69,55.53 ,2.29,0.5,5.093 ),2.);
d = min2( d, d1 );
}
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.x, i_BIT6, 0.119,0.,0.,0.993,-8.6,-2.19,-46.66,3.549,0.5,5.093 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT7, -0.25,-0.551,-0.688,0.401,-80.1,-15.9,120.65,18.917,18.917,18.917 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT8, 0.,0.,0.,1.,-8.6,8.2,79.6,5.,5.,21. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT9, 0.109,-0.195,-0.44,0.87,10.53,-2.73,87.08,5.,5.,5. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT0, 0.,0.,0.,1.,106.,-9.6,172.85,20.,20.,20. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT1, 0.,0.,0.,1.,8.9,8.2,119.57,23.5,6.,23.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT2, 0.,0.707,0.,0.707,71.4,8.2,159.56,5.,5.,21. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT3, 0.,0.,0.,1.,-9.1,1.07,-36.91,6.,3.,51. );
return dist < 10000. ? dist : -1.;
}
