// Generated by track editor Unity project
const vec3 Xc0 = vec3(124.9,34,130.5),Xc1 = vec3(137.98,10.02,219.71),Xc2 = vec3(-95.81,9.97,133.71),Xc3 = vec3(45.5,34.74,185.03);
const vec4 Xf0 = vec4(0,-0.707,0,0.707),Xf1 = vec4(0,0,0,1),Xf2 = vec4(0,0,0,1),Xf3 = vec4(0,-0.707,0,0.707),Xp0 = vec4(71.1,31.3,149.9,90),Xp1 = vec4(0);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.x / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj3( p, 0.,0.,0.,1.,0.,9.,-20. ,15.,30.,7.5,1. ) );
if( mod( g_traceBits.x / i_BIT7, 2. ) >= 1. )
d = min2( d, sdObj3( p, 0.,0.,0.,1.,138.2,9.,157.5 ,30.,30.,4.,1. ) );
if( mod( g_traceBits.x / i_BIT8, 2. ) >= 1. )
d = min2( d, sdObj2( p, -0.707,-0.707,0.,0.,122.5,9.,157.5 ,50.,-30.,-1.57,0.,2. ) );
if( mod( g_traceBits.x / i_BIT9, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.707,0.,0.707,-80.,9.,120. ,7.5,-15.,0.,1.,2. ) );
if( mod( g_traceBits.y / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-0.707,0.,0.707,-30.,9.,150. ,7.5,25.,0.,6.,0. ) );
if( mod( g_traceBits.y / i_BIT1, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.,1.,-95.,9.,135. ,7.5,-15.,0.,1.,2. ) );
if( mod( g_traceBits.y / i_BIT2, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-0.707,0.,0.707,-80.,9.,150. ,7.5,25.,0.,6.,0. ) );
if( mod( g_traceBits.y / i_BIT3, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.,1.,0.,9.,40. ,7.5,80.,0.,1.,2. ) );
if( mod( g_traceBits.y / i_BIT4, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,-0.707,0.707,42.5,9.,157.5 ,60.,-30.,-1.57,0.,2. ) );
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.x, i_BIT6, 0.,0.,0.,1.,0.,9.,-20.,16.,1.5,31. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT7, 0.,0.,0.,1.,138.2,9.,157.5,31.,1.5,31. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT8, -0.707,-0.707,0.,0.,122.5,-1.5,157.5,41.5,52.,41.5 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT9, 0.,0.707,0.,0.707,-80.,9.,123.25,12.75,9.5,12.75 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT0, 0.,-0.707,0.,0.707,-30.,9.,150.,8.5,1.5,26. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT1, 0.,0.,0.,1.,-91.75,9.,135.,12.75,9.5,12.75 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT2, 0.,-0.707,0.,0.707,-80.,9.,150.,8.5,1.5,26. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT3, 0.,0.,0.,1.,-35.75,9.,40.,45.25,9.5,45.25 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT4, 0.,0.,-0.707,0.707,42.5,-6.5,157.5,46.5,62.,46.5 );
return dist < 10000. ? dist : -1.;
}
