// Generated by track editor Unity project
const vec3 Xc0 = vec3(-120.51,20.33,239.8),Xc1 = vec3(115.06,9.52,-165.5),Xc2 = vec3(5.32,8.8,-87.93),Xc3 = vec3(0,8.8,84.9);
const vec4 Xf0 = vec4(0,0.361,0,0.932),Xf1 = vec4(0,-0.707,0,0.707),Xf2 = vec4(0,0.383,0,0.924),Xf3 = vec4(0,-0.707,0,0.707),Xp0 = vec4(4.7,29.5,-134.5,50);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.x / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.5,0.5,-0.5,0.5,15.,9.,-165.5 ,20.,-20.,-1.57,0.,2. ) );
if( mod( g_traceBits.x / i_BIT7, 2. ) >= 1. )
d = min2( d, sdObj2( p, -0.5,0.5,0.5,0.5,15.06,49.,-145.5 ,20.,-20.,-1.57,0.,2. ) );
if( mod( g_traceBits.x / i_BIT8, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,-0.707,-0.707,0.,35.,29.,-125.5 ,20.,-20.,-1.57,0.,2. ) );
if( mod( g_traceBits.x / i_BIT9, 2. ) >= 1. )
d = min2( d, sdObj2( p, -0.5,-0.5,-0.5,0.5,15.,9.,-105.5 ,20.,-20.,-1.57,0.,2. ) );
if( mod( g_traceBits.y / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.183,-0.683,-0.183,0.683,139.86,16.75,-165.5 ,5.,15.,15.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT1, 2. ) >= 1. )
d = min2( d, sdObj3( p, 0.,-0.707,0.,0.707,15.,9.,-165.5 ,20.,50.,5.,2. ) );
if( mod( g_traceBits.y / i_BIT2, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-1.,0.,0.,0.,9.,-5. ,15.,25.,0.,6.,1. ) );
if( mod( g_traceBits.y / i_BIT3, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-1.,0.,0.,0.,9.,-55. ,15.,25.,0.,2.,0. ) );
if( mod( g_traceBits.y / i_BIT4, 2. ) >= 1. )
{
vec2 d1 = opSubtract2(sdObj0( p, 0.,0.,0.,1.,0.,9.,55.2 ,5.,5.,10. ),sdObj1( p, 0.,0.,0.,1.,0.,9.,-5. ,15.,50.,0.,2.,1. ),6.);
d = min2( d, d1 );
}
if( mod( g_traceBits.y / i_BIT5, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj0( p, 0.183,-0.683,-0.183,0.683,122.54,6.75,-165.5 ,5.,0.5,10. ),sdObj0( p, 0.,-0.707,0.,0.707,115.,9.,-165.5 ,5.,0.5,10. ),5.);
d = min2( d, d1 );
}
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.x, i_BIT6, 0.5,0.5,-0.5,0.5,15.,8.5,-165.5,21.5,22.,21.5 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT7, -0.5,0.5,0.5,0.5,15.06,49.5,-145.5,21.5,22.,21.5 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT8, 0.,-0.707,-0.707,0.,35.5,29.,-125.5,21.5,22.,21.5 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT9, -0.5,-0.5,-0.5,0.5,15.,8.5,-105.5,21.5,22.,21.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT0, 0.183,-0.683,-0.183,0.683,139.86,16.75,-165.5,6.,6.,16. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT1, 0.,-0.707,0.,0.707,15.,9.,-165.5,21.,1.5,51. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT2, 0.,-1.,0.,0.,0.,9.,-5.,16.,1.5,26. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT3, 0.,-1.,0.,0.,0.,9.,-55.,16.,1.5,26. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT4, 0.,0.,0.,1.,0.,9.,-5.,20.,1.,51. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT5, 0.,-0.707,0.,0.707,115.,9.,-165.5,7.5,11.5,15.75 );
return dist < 10000. ? dist : -1.;
}
