// Generated by track editor Unity project
const vec3 Xc0 = vec3(0.44,0.13,53.7),Xc1 = vec3(23.56,8.03,162.8),Xc2 = vec3(65.47,7.93,166.48),Xc3 = vec3(122.56,9.77,207.71);
const vec4 Xf0 = vec4(0,0,0,1),Xf1 = vec4(0.12,-0.468,0.199,0.853),Xf2 = vec4(0.07,-0.704,0.07,0.704),Xf3 = vec4(0,-0.277,0,0.961),Xp0 = vec4(115.4,9.6,199.1,22.3);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.y / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.119,0.,0.,0.993,0.5,-2.19,-39.91 ,3.549,0.5,5.093 ) );
if( mod( g_traceBits.y / i_BIT1, 2. ) >= 1. )
d = min2( d, sdObj0( p, -0.25,-0.551,-0.688,0.401,-71.,-9.6,127.4 ,18.917,18.917,18.917 ) );
if( mod( g_traceBits.y / i_BIT2, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,0.5,8.2,86.35 ,4.,20.,80.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT3, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.109,-0.195,-0.44,0.87,19.63,-2.73,93.83 ,5.,5.,5. ) );
if( mod( g_traceBits.y / i_BIT4, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.,0.,0.,1.,115.1,-9.6,179.6 ,20.,20.,20. ) );
if( mod( g_traceBits.y / i_BIT5, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.,1.,0.5,8.2,126.32 ,4.,-40.,-0.5,1. ) );
if( mod( g_traceBits.y / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.707,0.,0.707,80.5,8.2,166.31 ,4.,20.,-80.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT7, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj1( p, 0.,0.,0.,1.,0.5,0.21,-30.12 ,4.,50.,0.,2.,1. ),sdObj0( p, 0.313,0.,0.,0.95,0.5,-2.69,62.28 ,2.29,0.5,5.093 ),2.);
d = min2( d, d1 );
}
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.y, i_BIT0, 0.119,0.,0.,0.993,0.5,-2.19,-39.91,3.549,0.5,5.093 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT1, -0.25,-0.551,-0.688,0.401,-71.,-9.6,127.4,18.917,18.917,18.917 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT2, 0.,0.,0.,1.,0.5,8.2,86.35,5.,5.,21. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT3, 0.109,-0.195,-0.44,0.87,19.63,-2.73,93.83,5.,5.,5. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT4, 0.,0.,0.,1.,115.1,-9.6,179.6,20.,20.,20. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT5, 0.,0.,0.,1.,18.,8.2,126.32,22.5,5.,22.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT6, 0.,0.707,0.,0.707,80.5,8.2,166.31,5.,5.,21. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT7, 0.,0.,0.,1.,0.,1.07,-30.16,6.,3.,51. );
return dist < 10000. ? dist : -1.;
}
