// Generated by track editor Unity project
vec2 t00( vec3 p )
{
return min2(opSmoothUnion2(sdObj0( quat(0.383,0.,0.,0.924)*(p-vec3(0.5,-1.42,64.26)), vec3(2.29,0.5,3.109)),sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,0,-130.6)), vec3(4,0.5,100),0.),2.),min2(sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,0,-130.6)), vec3(4,0.5,100),0.),min2(sdObj0( quat(0.383,0.,0.,0.924)*(p-vec3(0.5,-1.42,64.26)), vec3(2.29,0.5,3.109)),sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,5.65,87.7)), vec3(4,0.5,100),0.))));
}