// Generated by track editor Unity project
const vec3 Xc0 = vec3(-35.1,60.3,150.9),Xc1 = vec3(126.2,23.53,200.1),Xc2 = vec3(323.25,82.07,259.96),Xc3 = vec3(393.47,25.95,319.14);
const vec4 Xf0 = vec4(0,0,0,1),Xf1 = vec4(0,-0.69,0,0.723),Xf2 = vec4(0,0,0,1),Xf3 = vec4(0,-0.707,0,0.707),Xp0 = vec4(-29.4,43.1,150.9,72.7),Xp1 = vec4(324.7,50.2,260.1,39.1);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.x / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,-0.707,0.,0.707,256.1,24.,200. ,7.5,60.,0.,0.,2. ) );
if( mod( g_traceBits.x / i_BIT7, 2. ) >= 1. )
d = min2( d, sdObj3( p, 0.,0.,0.,1.,0.,9.,-12.3 ,15.,25.,7.5,1. ) );
if( mod( g_traceBits.x / i_BIT8, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.5,-0.5,-0.5,0.5,-37.5,39.,100. ,30.,0.5,1. ) );
if( mod( g_traceBits.x / i_BIT9, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.5,-0.5,-0.5,0.5,-38.,39.,200. ,30.,0.5,1. ) );
if( mod( g_traceBits.y / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj0( p, 0.,-0.707,0.,0.707,206.1,24.,200. ,7.5,0.5,25. ) );
if( mod( g_traceBits.y / i_BIT1, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.5,0.5,-0.5,0.5,-7.5,9.,100. ,30.,-30.,-1.57,0.,6. ) );
if( mod( g_traceBits.y / i_BIT2, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-0.707,0.,0.707,-8.,9.,200. ,30.,22.9,0.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT3, 2. ) >= 1. )
d = min2( d, sdObj2( p, -0.707,-0.707,0.,0.,331.1,24.,260. ,7.5,-30.,-1.57,0.,2. ) );
if( mod( g_traceBits.y / i_BIT4, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.5,0.5,-0.5,0.5,-8.,9.,200. ,30.,-30.,-1.57,0.,6. ) );
if( mod( g_traceBits.y / i_BIT5, 2. ) >= 1. )
d = min2( d, sdObj3( p, 0.,-0.707,0.,0.707,37.8,9.,200. ,30.,24.25,7.5,1. ) );
if( mod( g_traceBits.y / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj2( p, -0.707,0.707,0.,0.,323.6,84.,260. ,15.,-30.,-1.57,0.,2. ) );
if( mod( g_traceBits.y / i_BIT7, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.707,0.707,323.6,84.,260. ,15.,-30.,-1.57,0.,2. ) );
if( mod( g_traceBits.y / i_BIT8, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,-0.707,0.707,316.1,24.,260. ,7.5,-30.,-1.57,0.,2. ) );
if( mod( g_traceBits.y / i_BIT9, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,0.,9.,37.7 ,7.5,46.25,0.,2.,0. ) );
if( mod( g_traceBits.z / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.,1.,331.1,24.,260. ,7.5,-60.,0.,0.,2. ) );
if( mod( g_traceBits.z / i_BIT1, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj1( p, 0.183,-0.683,-0.183,0.683,93.84,6.75,200. ,7.5,10.,0.,2.,1. ),sdObj1( p, 0.,-0.707,0.,0.707,86.3,9.,200. ,7.5,10.,0.,2.,1. ),5.);
d = min2( d, d1 );
}
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.x, i_BIT6, 0.,-0.707,0.,0.707,256.1,24.,225.75,35.25,9.5,35.25 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT7, 0.,0.,0.,1.,0.,9.,-12.3,16.,1.5,26. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT8, 0.5,-0.5,-0.5,0.5,-37.5,39.,100.,30.,0.5,1. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT9, 0.5,-0.5,-0.5,0.5,-38.,39.,200.,30.,0.5,1. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT0, 0.,-0.707,0.,0.707,206.1,24.,200.,7.5,0.5,25. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT1, 0.5,0.5,-0.5,0.5,-7.5,8.5,100.,31.5,32.,31.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT2, 0.,-0.707,0.,0.707,-8.,9.,200.,31.,1.5,23.9 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT3, -0.707,-0.707,0.,0.,331.1,34.75,260.,20.25,9.5,20.25 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT4, 0.5,0.5,-0.5,0.5,-8.,8.5,200.,31.5,32.,31.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT5, 0.,-0.707,0.,0.707,37.8,9.,200.,31.,1.5,25.25 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT6, -0.707,0.707,0.,0.,323.6,77.,260.,24.,17.,24. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT7, 0.,0.,0.707,0.707,323.6,77.,260.,24.,17.,24. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT8, 0.,0.,-0.707,0.707,316.1,34.75,260.,20.25,9.5,20.25 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT9, 0.,0.,0.,1.,0.,9.,37.7,8.5,1.5,47.25 );
traceBox( ro, rd, dist, g_traceBits.z, i_BIT0, 0.,0.,0.,1.,356.85,24.,260.,35.25,9.5,35.25 );
traceBox( ro, rd, dist, g_traceBits.z, i_BIT1, 0.,-0.707,0.,0.707,86.3,9.,200.,12.25,11.5,15.75 );
return dist < 10000. ? dist : -1.;
}
