// Generated by track editor Unity project
const vec3 Xc0 = vec3(0.44,0.64,32.21);
const vec2 Xf0 = vec2(0,0);
const vec3 Xc1 = vec3(63.25,8.77,144.62);
const vec2 Xf1 = vec2(0,1.571);
const vec3 Xc2 = vec3(83.38,8.77,144.62);
const vec2 Xf2 = vec2(0,1.571);
const vec3 Xc3 = vec3(0.44,8.75,56.67);
const vec2 Xf3 = vec2(5.76,0);
vec2 Xmap( vec3 p )
{
return min2(opSmoothUnion2(sdObj0( quat(0.313,0.,0.,0.95)*(p-vec3(0.5,-2.73,43.43)), vec3(2.29,0.5,5.093)),sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,0.17,-52.03)), vec3(4,0.5,50),0.),2.),min2(sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,0.17,-52.03)), vec3(4,0.5,50),0.),min2(sdObj1( quat(0.,0.707,0.,0.707)*(p-vec3(80.5,8.2,144.41)), vec3(4,0.5,20),-80.),min2(sdObj0( quat(0.313,0.,0.,0.95)*(p-vec3(0.5,-2.73,43.43)), vec3(2.29,0.5,5.093)),min2(sdObj2( quat(0.,0.,0.,1.)*(p-vec3(0.5,8.2,104.42)), vec3(4,0.5,20),-40.,-0.5),min2(sdObj0( quat(0.109,-0.195,-0.44,0.87)*(p-vec3(19.63,-2.73,71.93)), vec3(5,5,5)),min2(sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,8.2,64.45)), vec3(4,0.5,20),80.),min2(sdObj0( quat(-0.25,-0.551,-0.688,0.401)*(p-vec3(-71,-9.6,105.5)), vec3(18.917,18.917,18.917)),sdObj0( quat(0.119,0.,0.,0.993)*(p-vec3(0.5,-2.19,-61.81)), vec3(3.549,0.5,5.093))))))))));
}