// Generated by track editor Unity project
const vec3 Xc0 = vec3(0,8.7,24),Xc1 = vec3(0,2.78,92.7),Xc2 = vec3(349.3,42.2,172.6),Xc3 = vec3(230.4,17.82,172.4);
const vec4 Xf0 = vec4(0,0,0,1),Xf1 = vec4(0,0,0,1),Xf2 = vec4(0,-0.707,0,0.707),Xf3 = vec4(0,-0.707,0,0.707),Xp0 = vec4(-33.6,77.3,206.5,40),Xp1 = vec4(0);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.x / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-0.707,0.,0.707,189.6,17.8,172.6 ,3.5,40.,0.,6.,0. ) );
if( mod( g_traceBits.x / i_BIT7, 2. ) >= 1. )
d = min2( d, sdObj3( p, 0.,0.,0.,1.,0.5,2.9,72.6 ,10.,10.,5.,2. ) );
if( mod( g_traceBits.x / i_BIT8, 2. ) >= 1. )
d = min2( d, sdObj2( p, 0.,0.,0.,1.,0.5,2.9,132.6 ,5.,-40.,-0.5,1.,2. ) );
if( mod( g_traceBits.x / i_BIT9, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,-0.707,0.,0.707,139.6,17.8,172.6 ,7.,25.,0.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT0, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,0.5,2.9,92.6 ,5.,20.,80.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT1, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.707,0.,0.707,80.5,2.9,172.6 ,5.,20.,-80.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT2, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,0.5,2.9,92.6 ,0.5,0.5,80.,2.,0. ) );
if( mod( g_traceBits.y / i_BIT3, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,0.5,9.,-6.1 ,10.,14.545,0.,2.,1. ) );
if( mod( g_traceBits.y / i_BIT4, 2. ) >= 1. )
{
vec2 d1 = opSubtract2(sdObj0( p, 0.,0.,0.,1.,0.72,3.94,58.3 ,4.,5.,5. ),sdObj1( p, 0.,0.,0.,1.,0.5,2.9,2.6 ,10.,35.,0.,2.,1. ),6.);
d = min2( d, d1 );
}
if( mod( g_traceBits.y / i_BIT5, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj1( p, 0.,-0.707,0.,0.707,269.6,17.8,172.6 ,7.,20.,0.,2.,1. ),sdObj0( p, 0.221,-0.672,-0.221,0.672,304.5,15.8,172.6 ,3.,0.5,5.093 ),2.);
d = min2( d, d1 );
}
if( mod( g_traceBits.y / i_BIT6, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj1( p, 0.,-0.707,0.,0.707,80.5,2.9,172.6 ,5.,10.,0.,2.,1. ),sdObj0( p, 0.221,-0.672,-0.221,0.672,94.84,0.9,172.6 ,4.,0.5,5.093 ),2.);
d = min2( d, d1 );
}
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.x, i_BIT6, 0.,-0.707,0.,0.707,189.6,17.8,172.6,4.5,1.5,41. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT7, 0.,0.,0.,1.,0.5,2.9,72.6,11.,1.5,11. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT8, 0.,0.,0.,1.,17.5,2.9,132.6,24.,7.,24. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT9, 0.,-0.707,0.,0.707,139.6,17.8,172.6,8.,1.5,26. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT0, 0.,0.,0.,1.,0.5,2.9,92.6,6.,6.,21. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT1, 0.,0.707,0.,0.707,80.5,2.9,172.6,6.,6.,21. );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT2, 0.,0.,0.,1.,0.5,2.9,92.6,1.5,1.5,1.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT3, 0.,0.,0.,1.,0.5,9.,-6.1,11.,1.5,15.545 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT4, 0.,0.,0.,1.,0.5,2.9,2.6,11.,3.,37.8 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT5, 0.,-0.707,0.,0.707,269.6,17.8,172.6,10.,5.,22.5 );
traceBox( ro, rd, dist, g_traceBits.y, i_BIT6, 0.,-0.707,0.,0.707,80.5,2.9,172.6,6.,5.,12.5 );
return dist < 10000. ? dist : -1.;
}
