// Generated by track editor Unity project
const vec3 Xc0 = vec3(0,-10,0),Xc1 = vec3(0,-10,0),Xc2 = vec3(0,-10,0),Xc3 = vec3(0,-10,0);
const vec4 Xf0 = vec4(0,0,0,1),Xf1 = vec4(0,0,0,1),Xf2 = vec4(0,0,0,1),Xf3 = vec4(0,0,0,1),Xp0 = vec4(0,0,0,0);
vec2 Xmap( vec3 p )
{
vec2 d = sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,5.65,87.7)), vec3(4,0.5,100) ,0. );
{
vec2 d1 = opSmoothUnion2(sdObj1( quat(0.,0.,0.,1.)*(p-vec3(0.5,0,-130.6)), vec3(4,0.5,100) ,0. ),sdObj0( quat(0.383,0.,0.,0.924)*(p-vec3(0.5,-1.42,64.26)), vec3(2.29,0.5,3.109)  ),2.);
d = min2( d, d1 );
}
return d;
}
