// Generated by track editor Unity project
const vec3 Xc0 = vec3(0.44,36.98,104.33),Xc1 = vec3(-55.43,46.6,191.46),Xc2 = vec3(-9,61.2,154.5),Xc3 = vec3(77.61,29.42,154.8);
const vec4 Xf0 = vec4(0,0,0,1),Xf1 = vec4(0,-0.707,0,0.707),Xf2 = vec4(0,-0.707,0,0.707),Xf3 = vec4(0,0,0,1),Xp0 = vec4(43.6,34.5,155.6,40),Xp1 = vec4(-55.6,50.6,155.6,40);
vec2 Xm( vec3 p )
{
vec2 d = vec2( 10000, 0 );
if( mod( g_traceBits.x / i_BIT6, 2. ) >= 1. )
d = min2( d, sdObj1( p, 0.,0.,0.,1.,0.,9.,-10. ,7.5,30.,0.,6.,1. ) );
if( mod( g_traceBits.x / i_BIT7, 2. ) >= 1. )
{
vec2 d1 = opSubtract2(sdObj4( p, -0.707,0.,0.,0.707,43.6,123.1,155.6 ,40.,40. ),sdObj0( p, -0.707,0.,0.,0.707,43.6,34.3,155.6 ,50.,50.,50. ),2.);
d = min2( d, d1 );
}
if( mod( g_traceBits.x / i_BIT8, 2. ) >= 1. )
{
vec2 d1 = opSmoothUnion2(sdObj1( p, 0.344,0.,0.,0.939,0.,6.75,57.54 ,7.5,10.,0.,6.,1. ),sdObj1( p, 0.,0.,0.,1.,0.,9.,50. ,7.5,10.,0.,6.,1. ),5.);
d = min2( d, d1 );
}
if( mod( g_traceBits.x / i_BIT9, 2. ) >= 1. )
{
vec2 d1 = opSubtract2(sdObj4( p, -0.707,0.,0.,0.707,-55.6,139.4,155.6 ,40.,40. ),sdObj0( p, -0.707,0.,0.,0.707,-55.6,50.6,155.6 ,50.,50.,50. ),2.);
d = min2( d, d1 );
}
return d;
}
float Xt( vec3 ro, vec3 rd, float dist )
{
traceBox( ro, rd, dist, g_traceBits.x, i_BIT6, 0.,0.,0.,1.,0.,9.,-10.,8.5,1.5,31. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT7, 0.,0.,0.,1.,43.6,6.7,96.1,75.,75.,75. );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT8, 0.,0.,0.,1.,0.,9.,50.,12.25,14.25,15.75 );
traceBox( ro, rd, dist, g_traceBits.x, i_BIT9, 0.,0.,0.,1.,-55.6,23.,96.1,75.,75.,75. );
return dist < 10000. ? dist : -1.;
}
